
<?php
$url_order = 'ASC';
if ($order_by == 'sell_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'sell_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'sell_money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'sell_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'sell_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'sell_comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>DANH SÁCH ĐƠN HÀNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('sell') ?>">Đơn hàng</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">

        <div class="add-box">

            <select id="sl_round" name="sl_round" style="width:90px">

             <?php 

                for ($k=1; $k < 13; $k++) { 

                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';

                }

             ?>

            </select>

            <select id="sl_staff" name="sl_staff" style="width:100px">

             <?php 

                $nam = date('Y');

                for ($k=($nam-5); $k < ($nam+5); $k++) { 

                    echo '<option value="'.$k.'">Năm '.$k.'</option>';

                }

             ?>

            </select>



            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

    </div>

    <div class="tablenav top">

        <div style="clear:both"></div>

        <div class="add-box">

                  

            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  

            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  

             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

        <div style="clear:both"></div>
        
        <div class="add-box">
            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>
        <div class="add-box" style="margin-right: 5px">
            <select style="width:120px" name="sl_nv" id="sl_nv">
                <option value="0">Khách hàng</option>
                <?php foreach ($customers as $sm) { ?>
                <option value="<?php echo $sm->customer_id ?>"><?php echo $sm->customer_name ?></option>
                <?php } ?>
            </select>
            
            
        </div>

      </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>

<table class="table_data" id="tblExport">
  <thead>
      <tr>
          <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
          <th class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'sell_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'sell_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_code','<?php echo $url_order ?>')">Số đơn hàng <?php if ($order_by == 'sell_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'sell_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_number','<?php echo $url_order ?>')">Số lượng <?php if ($order_by == 'sell_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_money','<?php echo $url_order ?>')">Thành tiền <?php if ($order_by == 'sell_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
             
          <?php if(!isset($disable_control)){ ?>
             
          <th  class="fix">&nbsp;</th>
          <?php } ?>
      </tr>
      
     </thead>
     <tbody>
      <?php $tong = 0; $tongtien = 0;
      foreach ($sells as $sell) : 
        $tong += $sell->sell_number;
      $tongtien += $sell->sell_money;
        ?>
          <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $sell->sell_id ?>" class="edit_tr">
              <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $sell->sell_id ?>"></td>
              <td class="fix"><?php echo $i++; ?></td>
              <td class="fix"  id="sell_date_<?php echo $sell->sell_id; ?>"><?php echo $lib->hien_thi_ngay_thang($sell->sell_date) ?></td>
              <td class="fix"  id="sell_code_<?php echo $sell->sell_id; ?>"><?php echo $sell->sell_code ?></td>
              <td class="fix"  id="sell_customer_<?php echo $sell->sell_id; ?>" data="<?php echo $sell->sell_customer ?>"><?php echo $sell->customer_name ?></td>
              <td class="fix"  id="sell_comment_<?php echo $sell->sell_id; ?>"><?php echo $sell->sell_comment ?></td>
              <td class="fix"  id="sell_number_<?php echo $sell->sell_id; ?>"><?php echo $sell->sell_number ?></td>
              <td class="fix"  id="sell_money_<?php echo $sell->sell_id; ?>"><?php echo $lib->formatMoney($sell->sell_money) ?></td>
              
              <?php if(!isset($disable_control)){ ?>
              <td class="pull-right">
                  <a href="<?php echo $this->url('sell/detail/'.$sell->sell_id) ?>" class="btn btn-sm btn-flat btn-info detail"><i class="fa fa-file-text-o"></i> Bảng kê</a>
                  <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                  <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $sell->sell_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
              </td>
              <?php } ?>
          </tr>
      <?php endforeach; ?>
      <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="6" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix" ><?php echo $lib->formatMoney($tong) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongtien) ?></td>
        </tr>
     </tbody>
  </table>


<?php
$this->helper('slidePaginator');
?>
<div class="add-field">

    <section class="content">

      <div class="row">

        <!-- left column -->

        <div class="col-md-12">

          <!-- general form elements -->

          <div class="box box-primary">

            <!-- /.box-header -->

            <!-- form start -->

            <form id="add_sell" role="form" method="post" action="" enctype="multipart/form-data">

              <div class="row">
                <div class="col-md-3 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="sell_date">Ngày</label>
                      <input class="ngay" type="text" id="sell_date"  name="sell_date" tabindex="1" required="required" >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-3 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="sell_code">Số đơn hàng</label>
                      <input type="text" id="sell_code"  name="sell_code" tabindex="2" required="required" >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-3 col-xs-6">

                  <div class="box-body">

                    <div class="form-group">

                      <label for="sell_customer">Khách hàng <a target="_blank" title="Thêm khách hàng" href="<?php echo $this->url('customer') ?>"><i class="fa fa-plus"></i></a></label>

                      <input type="text" autocomplete="off" id="sell_customer"  name="sell_customer" tabindex="3"  placeholder="Nhập tên hoặc * để chọn" required="required" >

                        <ul id="customer_list_id"></ul>

                    </div>


                  </div>

                  <!-- /.box-body -->


                </div>
                <div class="col-md-3 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="sell_comment">Nội dung</label>
                      <input type="text" id="sell_comment"  name="sell_comment" tabindex="4" >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <fieldset class="groupbox">
                      <legend>
                          <span><h3>Sản phẩm</h3></span>
                      </legend>

                      <table id="dataTable" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >
                          <tbody>
                          <tr>
                              <td><input type="checkbox" name="chk"></td>
                              <td>
                                  <table style="width:100%">
                                      <tr>
                                          <td>
                                            Mã sản phẩm<br>
                                              <input type="text" autocomplete="off" class="product" name="product[]" placeholder="Nhập tên hoặc * để chọn" tabindex="2" >
                                              <ul class="name_list_id"></ul>
                                          </td>
                                          
                                          <td>
                                            Số lượng <br>
                                            <input style="width:100px" type="text" class="sell_list_number number" name="sell_list_number[]" tabindex="3" >
                                          </td>

                                          <td>
                                            ĐVT <br>
                                            <input style="width:100px" type="text" class="sell_list_unit" name="sell_list_unit[]" tabindex="4" >
                                          </td>
                                          
                                          <td>
                                            Đơn giá <br>
                                              <input style="width:100px" type="text" class="sell_list_price number" name="sell_list_price[]" tabindex="5" >
                                          </td>
                                      </tr>
                                      
                                  </table>
                              </td>
                          </tr>
                      </tbody>
                      </table>
                  </fieldset>
                      <input type="button" value="Thêm" onclick="addRow('dataTable')">

                      <input type="button" value="Xóa" onclick="deleteRow('dataTable')">
                  </div>
                </div>
              </div>
              <?php if(!isset($disable_control)){ ?>

              <div class="row">

                <div class="col-md-12">

                    <div class="box-footer">

                    <input type="hidden" readonly id="yes" name="yes" required="required" >

                    <button type="submit" class="btn btn-primary" tabindex="5">Hoàn thành</button>

                    <button type="reset" class="btn" tabindex="6">Nhập lại</button>

                  </div>

                  <div class="box-footer">

                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

                  </div>

                </div>

              </div>

              <?php } ?>

            </form>

          </div>

          <!-- /.box -->



        </div>

        <!--/.col (left) -->

        

      </div>

      <!-- /.row -->

    </section>

    <!-- /.content -->

       

</div>

<script type="text/javascript">
$('html').click(function(e) {
    $('#customer_list_id').slideUp(200);
    $('.name_list_id').slideUp(200);
});

    $('.edit_tr').click(function(e){
        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var sell_code = $(this).find("#sell_code_"+$(this).attr('id')).text();
            var sell_date = $(this).find("#sell_date_"+$(this).attr('id')).text();
            var sell_comment = $(this).find("#sell_comment_"+$(this).attr('id')).text();
            var sell_customer = $(this).find("#sell_customer_"+$(this).attr('id')).attr('data');
            var sell_customer_name = $(this).find("#sell_customer_"+$(this).attr('id')).text();
            
            
            //alert(sell_code);
            $('#yes').val($(this).attr('id'));
            
            $('#sell_code').val(sell_code);
            $('#sell_customer').attr('data',sell_customer);
            $('#sell_customer').val(sell_customer_name);
            $('#sell_customer').attr('code',true);
            $('#sell_date').val(sell_date.replace(/\//g,"-"));
            $('#sell_comment').val(sell_comment);
            

            $('#dataTable tbody tr').remove();
        
            var sell_id = $(this).attr('id');
            $.ajax({
                url: '<?php echo BASE_URL ?>/sell/product',
                type: 'POST',
                data: {sell:sell_id},
                success:function(data){
                    //alert(data);
                    $('#dataTable tbody').append(data);
                    $('.product').keyup(function(){
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var keyword = $(this).val();
                        $.ajax({
                            url: '<?php echo BASE_URL ?>/sell/getProduct',
                            type: 'POST',
                            data: {keyword:keyword, offset:rowIndex},
                            success:function(data){
                                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                                $('.name_list_id:eq('+rowIndex+')').html(data);
                            }
                        });
                        if ($('.product:eq('+rowIndex+')').val() == "" || $('.product:eq('+rowIndex+')').attr('data') == "") {
                            
                            $('.product:eq('+rowIndex+')').attr('data',"");
                        }

                        
                    });

                $('.product').on('keydown', function() {
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var key = event.keyCode || event.charCode;

                        if( key == 8 || key == 46 ){
                            $('.product:eq('+rowIndex+')').attr('data',"");
                        }
                            
                      }); 

                
                   
                    $('.number').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9-.]/g, "")
                        ;
                      });
                    });
                   
                   $('.numbers').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9]/g, "")
                          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                        ;
                      });
                    });

                   function get_number(id){
                    return $(id).val().replace(/\,/g,'');
                  }
                  function set_item_other(item,value,vitri,unit,price) {
                      // change input value
                      $('.product:eq('+vitri+')').val(value);
                      $('.product:eq('+vitri+')').attr("data",item);
                      $('.sell_list_unit:eq('+vitri+')').val(unit);
                      $('.sell_list_price:eq('+vitri+')').val(price);

                      
                      // hide proposition list
                      $('.name_list_id').hide();
                      $('.product:eq('+vitri+')').focus();

                      $(".numbers").val(function(index, value) {
                      return value
                        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                      ;
                    });

                  }


                }
            });

            $( ".add-field" ).dialog( "open" );
        }
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
        
        $('#sell_code').val("");
        $('#sell_customer').attr('data',"");
        $('#sell_customer').val("");
        $('#sell_customer').attr('code',false);
        $('#sell_date').val("");
        $('#sell_comment').val("");
        
        $('input[name="chk"]').attr('data',"");
        $('input[type="text"]').attr('disabled',false);

        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


   $( ".add-field" ).dialog( "open" );

}


$(document).ready(function(){
            // Validate form
            $("#add_sell").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {

                  if ($('#sell_customer').attr('code') == 'false') {

                        $('#sell_customer').val("");

                        $('#sell_customer').focus();

                        return false;

                    };
                
                    var sell_code = $('#sell_code').attr('value');
                    var sell_date = $('#sell_date').attr('value');
                    var sell_comment = $('#sell_comment').attr('value');
                    var sell_customer = $('#sell_customer').attr('data');
                    

                    var product = [];
                    var product_code = [];
                    var product_id = [];
                    
                    var sell_list_number = [];
                    var sell_list_price = [];
                    var sell_list_unit = [];

                    $('.sell_list_number').each(function() { 
                        sell_list_number.push($(this).val());
                    });

                    $('.sell_list_price').each(function() { 
                        sell_list_price.push($(this).val());
                    });

                    $('.sell_list_unit').each(function() { 
                        sell_list_unit.push($(this).val());
                    });

                    $('.product').each(function(index) { 
                      product_code.push($(this).val());
                      product_id.push($(this).attr('data'));
                        
                    });


                    for (var i = 0; i < product_code.length; i++) {
                        product.push({'product_code':product_code[i], 'product_id':product_id[i], 'sell_list_number':sell_list_number[i], 'sell_list_price':sell_list_price[i], 'sell_list_unit':sell_list_unit[i]});
                        
                        
                    };

                    
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/sell/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            sell_code: sell_code,
                            sell_customer: sell_customer,
                            sell_date: sell_date,
                            sell_comment: sell_comment,
                            product: product,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại" ) {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#sell_name_'+yes).text(sell_name);
                                    $('#province_name_'+yes).text($('#province option:selected').text());
                                }
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="sell_name_'+parseInt(lastID+1)+'">'+sell_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
  $('#sell_customer').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/sell/getcustomer',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#sell_customer').val() == "" || $('#sell_customer').attr('data') == "") {
            //$('#loc_from').val("");
            $('#sell_customer').attr('data',"");
            $('#sell_customer').attr('code',false);
        }
      
   });

   $('.product').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/sell/getProduct',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.product:eq('+rowIndex+')').val() == "" || $('.product:eq('+rowIndex+')').attr('data') == "") {
            
            $('.product:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.product').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.product:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 


$('.product').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.product').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.product:eq('+rowIndex+')').attr('data',"");
        
        
    };
    
});


   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item_customer(value,name) {
    // change input value
    $('#sell_customer').val(name);
    $("#sell_customer").attr("data",value);
    $("#sell_customer").attr("code",'true');
    
    // hide proposition list
    $('#customer_list_id').hide();
    $('#sell_customer').focus();
     
}
function set_item_other(item,value,vitri,unit,price) {
      // change input value
      $('.product:eq('+vitri+')').val(value);
      $('.product:eq('+vitri+')').attr("data",item);
      $('.sell_list_unit:eq('+vitri+')').val(unit);
      $('.sell_list_price:eq('+vitri+')').val(price);

      
      // hide proposition list
      $('.name_list_id').hide();
      $('.product:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }
  
</script>
<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

         

    };  

    $(".ngay").datepicker(pickerOpts);



    

              

            

    

});



</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

$(".detail").click(function(){
    $("#winpopup").dialog({
        draggable:true,
        modal: true,
        autoOpen: false,
        width: "auto",
        maxHeight: $(window).height()-50,
        title:'Bảng kê nguyên vật liệu',
        
    });
    $("#winpopup").load($(this).attr('href'));
    $("#winpopup").dialog("open");
     
    return false;
});
</script>
</div>

<script type="text/javascript">
var l = "<?php echo $limit ?>";
$('#chonloc option[value='+l+']').attr('selected','selected');

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Đơn hàng",
    hide: 'fold',
    show: 'blind'
});



function addRow(tableID){
  var checked = 0;
  if ($('.check_seri:first').is(':checked')) {
    checked = 1;
  }

    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.product:last').attr('disabled',false);
    $('.product:last').attr('data',"");
    $('.product:last').val("");
    $('.sell_list_price:last').val("");
    $('.sell_list_number:last').val("");
    
    
    $('input[name="chk"]:last').attr('data',"");
    $('input[name="chk"]:last').attr('tabindex',0);
    $('input[name="chk"]:last').attr('title',"");
    $('input[name="chk"]:last').attr('class',"");
    $('input[name="chk"]:last').attr('alt',0);

    $('.product').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/sell/getProduct',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.product:eq('+rowIndex+')').val() == "" || $('.product:eq('+rowIndex+')').attr('data') == "") {
            
            $('.product:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.product').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.product:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 


$('.product').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.product').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.product:eq('+rowIndex+')').attr('data',"");
        
    };
    
});

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

   function get_number(id){
    return $(id).val().replace(/\,/g,'');
  }
  function set_item_other(item,value,vitri,unit,price) {
      // change input value
      $('.product:eq('+vitri+')').val(value);
      $('.product:eq('+vitri+')').attr("data",item);
      $('.sell_list_unit:eq('+vitri+')').val(unit);
      $('.sell_list_price:eq('+vitri+')').val(price);

      
      // hide proposition list
      $('.name_list_id').hide();
      $('.product:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }


}
function deleteRow(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                  if(rowCount<=1){
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    else if(chkbox.getAttribute("data") > 0){
                        
                            var sell = chkbox.getAttribute("data");
                            var product = chkbox.getAttribute("alt");
                            $.post("<?php echo BASE_URL ?>/sell/deleteproduct", {sell: sell, product: product},
                               function(data){
                                //alert(data);
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
            }
        }
    }
    catch(e){
        alert(e);
    }
}

</script>

<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
$(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );



         },

         

    };  

    $("#batdau").datepicker(pickerOpts);



    var pickerOpts4 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );

                

         },

         

    };  

    $("#ketthuc").datepicker(pickerOpts4);

              

            

    

});

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

var tt = "<?php echo $kh ?>";
$('#sl_nv option[value='+tt+']').attr('selected','selected');


var v = "<?php echo $vong ?>";

$('#sl_round option[value='+v+']').attr('selected','selected');



var tt = "<?php echo $trangthai ?>";

$('#sl_staff option[value='+tt+']').attr('selected','selected');

</script>
<script type="text/javascript">

    

    $('#sl_round').change(function(){

        var m = $(this).val();

        var y = $('#sl_staff').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });



    $('#sl_staff').change(function(){

        var y = $(this).val();

        var m = $('#sl_round').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });




</script>