
<?php
$url_order = 'ASC';
if ($order_by == 'product_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'product_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'product_price')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'product_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>SẢN PHẨM</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('product') ?>">Sản phẩm</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>

<table class="table_data" id="tblExport">
  <thead>
      <tr>
          <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
          <th class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','product_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'product_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','product_code','<?php echo $url_order ?>')">Mã sản phẩm <?php if ($order_by == 'product_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','product_number','<?php echo $url_order ?>')">Khối lượng <?php if ($order_by == 'product_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
          <th  class="fix">
              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','product_price','<?php echo $url_order ?>')">Giá trị <?php if ($order_by == 'product_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
          </th>
             
          <?php if(!isset($disable_control)){ ?>
             
          <th  class="fix">&nbsp;</th>
          <?php } ?>
      </tr>
      
     </thead>
     <tbody>
      <?php foreach ($products as $product) : ?>
          <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $product->product_id ?>" class="edit_tr">
              <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $product->product_id ?>"></td>
              <td class="fix"><?php echo $i++; ?></td>
              <td class="fix"  id="product_code_<?php echo $product->product_id; ?>"><?php echo $product->product_code ?></td>
              <td class="fix"  id="product_number_<?php echo $product->product_id; ?>"><?php echo $product->product_number ?></td>
              <td class="fix"  id="product_price_<?php echo $product->product_id; ?>"><?php echo $lib->formatMoney($product->product_price) ?></td>
              
              <?php if(!isset($disable_control)){ ?>
              <td class="pull-right">
                  <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                  <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $product->product_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
              </td>
              <?php } ?>
          </tr>
      <?php endforeach; ?>
     </tbody>
  </table>


<?php
$this->helper('slidePaginator');
?>
<div class="add-field">

    <section class="content">

      <div class="row">

        <!-- left column -->

        <div class="col-md-12">

          <!-- general form elements -->

          <div class="box box-primary">

            <!-- /.box-header -->

            <!-- form start -->

            <form id="add_product" role="form" method="post" action="" enctype="multipart/form-data">

              <div class="row">

                <div class="col-md-12 col-xs-12">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="product_code">Mã sản phẩm</label>
                      <input type="text" id="product_code"  name="product_code" tabindex="1" required="required" >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <fieldset class="groupbox">
                      <legend>
                          <span><h3>Nguyên vật liệu</h3></span>
                      </legend>

                      <table id="dataTable" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >
                          <tbody>
                          <tr>
                              <td><input type="checkbox" name="chk"></td>
                              <td>
                                  <table style="width:100%">
                                      <tr>
                                          <td>
                                            Tên <br>
                                              <input type="text" autocomplete="off" class="spare_part" name="spare_part[]" placeholder="Nhập tên hoặc * để chọn" tabindex="2" >
                                              <ul class="name_list_id"></ul>
                                          </td>
                                          
                                          <td>
                                            Số lượng <br>
                                            <input style="width:100px" type="text" class="spare_part_number number" name="spare_part_number[]" tabindex="3" >
                                          </td>

                                          <td>
                                            ĐVT <br>
                                            <input style="width:100px" type="text" class="spare_part_unit" name="spare_part_unit[]" tabindex="4" >
                                          </td>
                                          
                                          <td>
                                            Đơn giá <br>
                                              <input style="width:100px" type="text" class="spare_part_price number" name="spare_part_price[]" tabindex="5" >
                                          </td>
                                      </tr>
                                      
                                  </table>
                              </td>
                          </tr>
                      </tbody>
                      </table>
                  </fieldset>
                      <input type="button" value="Thêm" onclick="addRow('dataTable')">

                      <input type="button" value="Xóa" onclick="deleteRow('dataTable')">
                  </div>
                </div>
              </div>
              <?php if(!isset($disable_control)){ ?>

              <div class="row">

                <div class="col-md-12">

                    <div class="box-footer">

                    <input type="hidden" readonly id="yes" name="yes" required="required" >

                    <button type="submit" class="btn btn-primary" tabindex="2">Hoàn thành</button>

                    <button type="reset" class="btn" tabindex="3">Nhập lại</button>

                  </div>

                  <div class="box-footer">

                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

                  </div>

                </div>

              </div>

              <?php } ?>

            </form>

          </div>

          <!-- /.box -->



        </div>

        <!--/.col (left) -->

        

      </div>

      <!-- /.row -->

    </section>

    <!-- /.content -->

       

</div>

<script type="text/javascript">
$('html').click(function(e) {
    
    $('.name_list_id').slideUp(200);
});

    $('.edit_tr').click(function(e){
        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var product_code = $(this).find("#product_code_"+$(this).attr('id')).text();
            
            
            //alert(product_code);
            $('#yes').val($(this).attr('id'));
            
            $('#product_code').val(product_code);
            

            $('#dataTable tbody tr').remove();
        
            var product_id = $(this).attr('id');
            $.ajax({
                url: '<?php echo BASE_URL ?>/product/spare',
                type: 'POST',
                data: {product:product_id},
                success:function(data){
                    //alert(data);
                    $('#dataTable tbody').append(data);
                    $('.spare_part').keyup(function(){
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var keyword = $(this).val();
                        $.ajax({
                            url: '<?php echo BASE_URL ?>/product/getSpare',
                            type: 'POST',
                            data: {keyword:keyword, offset:rowIndex},
                            success:function(data){
                                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                                $('.name_list_id:eq('+rowIndex+')').html(data);
                            }
                        });
                        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
                            
                            $('.spare_part:eq('+rowIndex+')').attr('data',"");
                        }

                        
                    });

                $('.spare_part').on('keydown', function() {
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var key = event.keyCode || event.charCode;

                        if( key == 8 || key == 46 ){
                            $('.spare_part:eq('+rowIndex+')').attr('data',"");
                        }
                            
                      }); 

                
                   
                    $('.number').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9-.]/g, "")
                        ;
                      });
                    });
                   
                   $('.numbers').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9]/g, "")
                          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                        ;
                      });
                    });

                   function get_number(id){
                    return $(id).val().replace(/\,/g,'');
                  }
                  function set_item_other(item,value,vitri,unit,price) {
                      // change input value
                      $('.spare_part:eq('+vitri+')').val(value);
                      $('.spare_part:eq('+vitri+')').attr("data",item);
                      $('.spare_part_unit:eq('+vitri+')').val(unit);
                      $('.spare_part_price:eq('+vitri+')').val(price);

                      
                      // hide proposition list
                      $('.name_list_id').hide();
                      $('.spare_part:eq('+vitri+')').focus();

                      $(".numbers").val(function(index, value) {
                      return value
                        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                      ;
                    });

                  }


                }
            });

            $( ".add-field" ).dialog( "open" );
        }
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
        
        $('#product_code').val("");
        
        $('input[name="chk"]').attr('data',"");
        $('input[type="text"]').attr('disabled',false);

        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


   $( ".add-field" ).dialog( "open" );

}


$(document).ready(function(){
            // Validate form
            $("#add_product").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var product_code = $('#product_code').attr('value');
                    

                    var spare_part = [];
                    var spare_part_name = [];
                    var spare_part_id = [];
                    
                    var spare_part_number = [];
                    var spare_part_price = [];
                    var spare_part_unit = [];

                    $('.spare_part_number').each(function() { 
                        spare_part_number.push($(this).val());
                    });

                    $('.spare_part_price').each(function() { 
                        spare_part_price.push($(this).val());
                    });

                    $('.spare_part_unit').each(function() { 
                        spare_part_unit.push($(this).val());
                    });

                    $('.spare_part').each(function(index) { 
                      spare_part_name.push($(this).val());
                      spare_part_id.push($(this).attr('data'));
                        
                    });


                    for (var i = 0; i < spare_part_name.length; i++) {
                        spare_part.push({'spare_part_name':spare_part_name[i], 'spare_part_id':spare_part_id[i], 'spare_part_number':spare_part_number[i], 'spare_part_price':spare_part_price[i], 'spare_part_unit':spare_part_unit[i]});
                        
                        
                    };

                    
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/product/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            product_code: product_code,
                            spare_part: spare_part,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại" ) {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#product_name_'+yes).text(product_name);
                                    $('#province_name_'+yes).text($('#province option:selected').text());
                                }
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="product_name_'+parseInt(lastID+1)+'">'+product_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
  
   $('.spare_part').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/product/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.spare_part').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 


$('.spare_part').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        
        
    };
    
});


   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item_other(item,value,vitri,unit,price) {
      // change input value
      $('.spare_part:eq('+vitri+')').val(value);
      $('.spare_part:eq('+vitri+')').attr("data",item);
      $('.spare_part_unit:eq('+vitri+')').val(unit);
      $('.spare_part_price:eq('+vitri+')').val(price);

      
      // hide proposition list
      $('.name_list_id').hide();
      $('.spare_part:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }
  
</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
</script>
</div>

<script type="text/javascript">
var l = "<?php echo $limit ?>";
$('#chonloc option[value='+l+']').attr('selected','selected');

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Thông tin sản phẩm",
    hide: 'fold',
    show: 'blind'
});



function addRow(tableID){
  var checked = 0;
  if ($('.check_seri:first').is(':checked')) {
    checked = 1;
  }

    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.spare_part:last').attr('disabled',false);
    $('.spare_part:last').attr('data',"");
    $('.spare_part:last').val("");
    $('.spare_part_price:last').val("");
    $('.spare_part_number:last').val("");
    
    
    $('input[name="chk"]:last').attr('data',"");
    $('input[name="chk"]:last').attr('tabindex',0);
    $('input[name="chk"]:last').attr('title',"");
    $('input[name="chk"]:last').attr('class',"");
    $('input[name="chk"]:last').attr('alt',0);

    $('.spare_part').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/product/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.spare_part').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 


$('.spare_part').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        
    };
    
});

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

   function get_number(id){
    return $(id).val().replace(/\,/g,'');
  }
  function set_item_other(item,value,vitri,unit,price) {
      // change input value
      $('.spare_part:eq('+vitri+')').val(value);
      $('.spare_part:eq('+vitri+')').attr("data",item);
      $('.spare_part_unit:eq('+vitri+')').val(unit);
      $('.spare_part_price:eq('+vitri+')').val(price);

      
      // hide proposition list
      $('.name_list_id').hide();
      $('.spare_part:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }


}
function deleteRow(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                  if(rowCount<=1){
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    else if(chkbox.getAttribute("data") > 0){
                        
                            var product = chkbox.getAttribute("data");
                            var spare_part = chkbox.getAttribute("alt");
                            $.post("<?php echo BASE_URL ?>/product/deletespare", {product: product, spare_part: spare_part},
                               function(data){
                                //alert(data);
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
            }
        }
    }
    catch(e){
        alert(e);
    }
}

</script>

<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
  
var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');


</script>
