<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

  <title><?php echo isset($title) ? $title : null ?></title>

  <meta name="keywords" content="Logistics, Xuất Khẩu, Nhập Khẩu, Xuất Nhập Khẩu, Vận Chuyển Hàng Hóa, Vận Chuyển, Hàng Siêu Trọng, Salan, Xà Lan, Sà Lan, Vận Chuyển Sà Lan, Thủ Tục Hải Quan, Hải Quan, Thông Quan, Mở Tờ Khai, Hun Trùng, Đóng Cont, Đóng Hàng, Forwarder, Stufffing, Unstuffing, Export, Import, Terminal, Port, Sea Port, Transhit, Transhipment, OOG, Over Weight, Over Hight, Over Length, Barge, Barging, Barge team, Barge Fleet, Inland Water Way, IWW, Ship, Vessel, Canoe, River, Channal, Pilot, Boarding Agent, Đại lý tàu, Husbanding Agent, Cambudia, Barging Service, Customs, Customs transhipment, Customs Clearance, EDI, Manifest, E-Manifest, chỉnh sửa Manifest, Adjust Manifest, Inbound, Outbound, Cargo, container, 20', 40', Reefer container, Flatrach, Tank, Hàng Quá Khổ, Cấm Tải, Chất lượng,">

  <meta name="description" content="<?php echo isset($title) ? $title.' - ' : null ?>Logistics - Vận chuyển - Thủ tục hải quan - Manifest - Container">

  <meta name="generator" content="Tan Cang Mien Trung">

  <link href="<?php BASE_URL ?>/public/img/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon">

  <!-- Tell the browser to be responsive to screen width -->

  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- Bootstrap 3.3.6 -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/bootstrap/css/bootstrap.min.css">

  <!-- Font Awesome -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Ionicons -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  <!-- Morris chart -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.css">

  <!-- Theme style -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/AdminLTE.min.css">

  <!-- AdminLTE Skins. Choose a skin from the css/skins

       folder instead of downloading all of them to reduce the load. -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/skins/_all-skins.min.css">



  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->

  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

  <!--[if lt IE 9]>

  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

  <![endif]-->

  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/style.css">

  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/js/ui/jquery-ui.css">

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery-1.7.2.min.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/ui/jquery-ui.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/html5.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.form.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.validate.min.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/custom.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/localization/messages_vi.js"></script>

  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.battatech.excelexport.js"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/chosen/chosen.css">
  <script src="<?php echo BASE_URL ?>/public/js/chosen/chosen.jquery.js" type="text/javascript"></script>



  <style type="text/css">

    ul,ol{padding:0;margin:0px;}

    ul ul,ul ol,ol ol,ol ul{margin-bottom:0;}

    li {line-height: 18px;}

  </style>

  <style type="text/css">

  .pagination{height:36px;margin:18px 0;}

  .pagination ul{display:inline-block;*display:inline;*zoom:1;margin-left:0;margin-bottom:0;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;-webkit-box-shadow:0 1px 2px rgba(0, 0, 0, 0.05);-moz-box-shadow:0 1px 2px rgba(0, 0, 0, 0.05);box-shadow:0 1px 2px rgba(0, 0, 0, 0.05);}

  .pagination li{display:inline;white-space: nowrap;}

  .pagination a{float:left;padding:0 14px;line-height:34px;text-decoration:none;border:1px solid #ddd;border-left-width:0;}

  .pagination a:hover,.pagination .active a{background-color:#f5f5f5;}

  .pagination .active a{color:#999999;cursor:default;}

  .pagination .disabled a,.pagination .disabled a:hover{color:#999999;background-color:transparent;cursor:default;}

  .pagination li:first-child a{border-left-width:1px;-webkit-border-radius:3px 0 0 3px;-moz-border-radius:3px 0 0 3px;border-radius:3px 0 0 3px;}

  .pagination li:last-child a{-webkit-border-radius:0 3px 3px 0;-moz-border-radius:0 3px 3px 0;border-radius:0 3px 3px 0;}

  .pagination-centered{text-align:center;}

  .pagination-right{text-align:right;}

  a:hover{color:#07ACFF; cursor:pointer}



  button,input,select,textarea{margin:0;font-size:100%;vertical-align:middle;}

  button,input{*overflow:visible;line-height:normal;}

  button::-moz-focus-inner,input::-moz-focus-inner{padding:0;border:0;}

  button,input[type="button"],input[type="reset"],input[type="submit"]{cursor:pointer;-webkit-appearance:button;}

  input[type="search"],input[type="text"],input[type="number"],input[type="email"],input[type="password"]{-webkit-appearance:textfield;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;}



  legend{display:block;line-height:36px;}

  label,input,button,select,textarea{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;font-weight:normal;}

  label{display:block;margin-bottom:5px;color:#333333;}

  input,textarea,select,.uneditable-input{display:inline-block;width:190px;height:18px;padding:5px;margin-bottom:9px;font-size:13px;line-height:18px;color:#555555;border:1px solid #ccc;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;}

  .uneditable-textarea{width:auto;height:auto;}

  /* label input,label textarea,label select{display:block;} */

  input[type="image"],input[type="checkbox"],input[type="radio"]{width:auto;height:auto;padding:0;margin:3px 0;*margin-top:0;line-height:normal;border:0;cursor:pointer;-webkit-border-radius:0;-moz-border-radius:0;border-radius:0;}

  input[type="file"]{padding:initial;line-height:initial;border:initial;background-color:#ffffff;background-color:initial;-webkit-box-shadow:none;-moz-box-shadow:none;box-shadow:none;}

  input[type="button"],input[type="reset"],input[type="submit"]{width:auto;height:auto;}

  select,input[type="file"]{height:28px;*margin-top:4px;line-height:28px;}

  select{width:100%;background-color:#ffffff;}

  select[multiple],select[size]{height:auto;}

  input[type="image"]{-webkit-box-shadow:none;-moz-box-shadow:none;box-shadow:none;}

  textarea{height:auto;}

  input[type="hidden"]{display:none;}

  .radio,.checkbox{padding-left:18px;}

  .radio input[type="radio"],.checkbox input[type="checkbox"]{float:left;margin-left:-18px;}

  .controls>.radio:first-child,.controls>.checkbox:first-child{padding-top:5px;}

  .radio.inline,.checkbox.inline{display:inline-block;margin-bottom:0;vertical-align:middle;}

  .radio.inline+.radio.inline,.checkbox.inline+.checkbox.inline{margin-left:10px;}

  .controls>.radio.inline:first-child,.controls>.checkbox.inline:first-child{padding-top:0;}

  input,textarea{-webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075);-moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075);box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075);-webkit-transition:border linear 0.2s,box-shadow linear 0.2s;-moz-transition:border linear 0.2s,box-shadow linear 0.2s;-ms-transition:border linear 0.2s,box-shadow linear 0.2s;-o-transition:border linear 0.2s,box-shadow linear 0.2s;transition:border linear 0.2s,box-shadow linear 0.2s;}

  input:focus,textarea:focus{border-color:rgba(82, 168, 236, 0.8);-webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075),0 0 8px rgba(82, 168, 236, 0.6);-moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075),0 0 8px rgba(82, 168, 236, 0.6);box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075),0 0 8px rgba(82, 168, 236, 0.6);outline:0;outline:thin dotted \9;}

  input[type="file"]:focus,input[type="checkbox"]:focus,select:focus{-webkit-box-shadow:none;-moz-box-shadow:none;box-shadow:none;outline:thin dotted;outline:5px auto -webkit-focus-ring-color;outline-offset:-2px;}

  .input-mini{width:60px;}

  .input-small{width:90px;}

  .input-medium{width:150px;}

  .input-large{width:210px;}

  .input-xlarge{width:270px;}

  .input-xxlarge{width:530px;}

  input[class*="span"],select[class*="span"],textarea[class*="span"],.uneditable-input{float:none;margin-left:0;}

  input.span1,textarea.span1,.uneditable-input.span1{width:50px;}

  input.span2,textarea.span2,.uneditable-input.span2{width:130px;}

  input.span3,textarea.span3,.uneditable-input.span3{width:210px;}

  input.span4,textarea.span4,.uneditable-input.span4{width:290px;}

  input.span5,textarea.span5,.uneditable-input.span5{width:370px;}

  input.span6,textarea.span6,.uneditable-input.span6{width:450px;}

  input.span7,textarea.span7,.uneditable-input.span7{width:530px;}

  input.span8,textarea.span8,.uneditable-input.span8{width:610px;}

  input.span9,textarea.span9,.uneditable-input.span9{width:690px;}

  input.span10,textarea.span10,.uneditable-input.span10{width:770px;}

  input.span11,textarea.span11,.uneditable-input.span11{width:850px;}

  input.span12,textarea.span12,.uneditable-input.span12{width:930px;}

  input[disabled],select[disabled],textarea[disabled],input[readonly],select[readonly],textarea[readonly]{background-color:#f5f5f5;border-color:#ddd;cursor:not-allowed;}

  .control-group.warning>label,.control-group.warning .help-block,.control-group.warning .help-inline{color:#c09853;}

  .control-group.warning input,.control-group.warning select,.control-group.warning textarea{color:#c09853;border-color:#c09853;}.control-group.warning input:focus,.control-group.warning select:focus,.control-group.warning textarea:focus{border-color:#a47e3c;-webkit-box-shadow:0 0 6px #dbc59e;-moz-box-shadow:0 0 6px #dbc59e;box-shadow:0 0 6px #dbc59e;}

  .control-group.warning .input-prepend .add-on,.control-group.warning .input-append .add-on{color:#c09853;background-color:#fcf8e3;border-color:#c09853;}

  .control-group.error>label,.control-group.error .help-block,.control-group.error .help-inline{color:#b94a48;}

  .control-group.error input,.control-group.error select,.control-group.error textarea{color:#b94a48;border-color:#b94a48;}.control-group.error input:focus,.control-group.error select:focus,.control-group.error textarea:focus{border-color:#953b39;-webkit-box-shadow:0 0 6px #d59392;-moz-box-shadow:0 0 6px #d59392;box-shadow:0 0 6px #d59392;}

  .control-group.error .input-prepend .add-on,.control-group.error .input-append .add-on{color:#b94a48;background-color:#f2dede;border-color:#b94a48;}

  .control-group.success>label,.control-group.success .help-block,.control-group.success .help-inline{color:#468847;}

  .control-group.success input,.control-group.success select,.control-group.success textarea{color:#468847;border-color:#468847;}.control-group.success input:focus,.control-group.success select:focus,.control-group.success textarea:focus{border-color:#356635;-webkit-box-shadow:0 0 6px #7aba7b;-moz-box-shadow:0 0 6px #7aba7b;box-shadow:0 0 6px #7aba7b;}

  .control-group.success .input-prepend .add-on,.control-group.success .input-append .add-on{color:#468847;background-color:#dff0d8;border-color:#468847;}

  input:focus:required:invalid,textarea:focus:required:invalid,select:focus:required:invalid{color:#b94a48;border-color:#ee5f5b;}input:focus:required:invalid:focus,textarea:focus:required:invalid:focus,select:focus:required:invalid:focus{border-color:#e9322d;-webkit-box-shadow:0 0 6px #f8b9b7;-moz-box-shadow:0 0 6px #f8b9b7;box-shadow:0 0 6px #f8b9b7;}

  .form-actions{padding:17px 20px 18px;margin-top:18px;margin-bottom:18px;background-color:#f5f5f5;border-top:1px solid #ddd;}

  .uneditable-input{display:block;background-color:#ffffff;border-color:#eee;-webkit-box-shadow:inset 0 1px 2px rgba(0, 0, 0, 0.025);-moz-box-shadow:inset 0 1px 2px rgba(0, 0, 0, 0.025);box-shadow:inset 0 1px 2px rgba(0, 0, 0, 0.025);cursor:not-allowed;}

  :-moz-placeholder{color:#999999;}

  ::-webkit-input-placeholder{color:#999999;}

  .help-block{margin-top:5px;margin-bottom:0;color:#999999;}

  .help-inline{display:inline-block;*display:inline;*zoom:1;margin-bottom:9px;vertical-align:middle;padding-left:5px;}

  .input-prepend,.input-append{margin-bottom:5px;*zoom:1;}.input-prepend:before,.input-append:before,.input-prepend:after,.input-append:after{display:table;content:"";}

  .input-prepend:after,.input-append:after{clear:both;}

  .input-prepend input,.input-append input,.input-prepend .uneditable-input,.input-append .uneditable-input{-webkit-border-radius:0 3px 3px 0;-moz-border-radius:0 3px 3px 0;border-radius:0 3px 3px 0;}.input-prepend input:focus,.input-append input:focus,.input-prepend .uneditable-input:focus,.input-append .uneditable-input:focus{position:relative;z-index:2;}

  .input-prepend .uneditable-input,.input-append .uneditable-input{border-left-color:#ccc;}

  .input-prepend .add-on,.input-append .add-on{float:left;display:block;width:auto;min-width:16px;height:18px;margin-right:-1px;padding:5px;font-weight:normal;line-height:18px;color:#999999;text-align:center;text-shadow:0 1px 0 #ffffff;background-color:#f5f5f5;border:1px solid #ccc;-webkit-border-radius:3px 0 0 3px;-moz-border-radius:3px 0 0 3px;border-radius:3px 0 0 3px;}

  .input-prepend .active,.input-append .active{background-color:#a9dba9;border-color:#46a546;}

  .input-prepend .add-on{*margin-top:1px;}

  .input-append input,.input-append .uneditable-input{float:left;-webkit-border-radius:3px 0 0 3px;-moz-border-radius:3px 0 0 3px;border-radius:3px 0 0 3px;}

  .input-append .uneditable-input{border-right-color:#ccc;}

  .input-append .add-on{margin-right:0;margin-left:-1px;-webkit-border-radius:0 3px 3px 0;-moz-border-radius:0 3px 3px 0;border-radius:0 3px 3px 0;}

  .input-append input:first-child{*margin-left:-160px;}.input-append input:first-child+.add-on{*margin-left:-21px;}

  .search-query{padding-left:14px;padding-right:14px;margin-bottom:0;-webkit-border-radius:14px;-moz-border-radius:14px;border-radius:14px;}

  .form-search input,.form-inline input,.form-horizontal input,.form-search textarea,.form-inline textarea,.form-horizontal textarea,.form-search select,.form-inline select,.form-horizontal select,.form-search .help-inline,.form-inline .help-inline,.form-horizontal .help-inline,.form-search .uneditable-input,.form-inline .uneditable-input,.form-horizontal .uneditable-input{display:inline-block;margin-bottom:0;}

  .form-search label,.form-inline label,.form-search .input-append,.form-inline .input-append,.form-search .input-prepend,.form-inline .input-prepend{display:inline-block;}

  .form-search .input-append .add-on,.form-inline .input-prepend .add-on,.form-search .input-append .add-on,.form-inline .input-prepend .add-on{vertical-align:middle;}

  .control-group{margin-bottom:9px;}

  .form-horizontal legend+.control-group{margin-top:18px;-webkit-margin-top-collapse:separate;}

  .form-horizontal .control-group{margin-bottom:18px;*zoom:1;}.form-horizontal .control-group:before,.form-horizontal .control-group:after{display:table;content:"";}

  .form-horizontal .control-group:after{clear:both;}

  .form-horizontal .control-group>label{float:left;width:140px;padding-top:5px;text-align:right;}

  .form-horizontal .controls{margin-left:160px;}

  .form-horizontal .form-actions{padding-left:160px;}



  ul {

    list-style: disc;

  }

  ul {

      padding: 0;

      margin: 0px;

  }

  .ui-dialog{

    z-index: 999999;

  }

  .fixed-scrollbar {

      overflow-x: auto;

      overflow-y: hidden;

  }

  </style>

  <script type="text/javascript">

  $(function($){

      var scrollbar = $('<div id="fixed-scrollbar"><div></div></div>').appendTo($(document.body));

      scrollbar.hide().css({

          overflowX:'auto',

          position:'fixed',

          width:'100%',

          bottom:0

      });

      var fakecontent = scrollbar.find('div');

      

      function top(e) {

          return e.offset().top;

      }



      function bottom(e) {

          return e.offset().top + e.height();

      }

      

      var active = $([]);

      function find_active() {

          scrollbar.show();

          var active = $([]);

          $('.fixed-scrollbar').each(function() {

              if (top($(this)) < top(scrollbar) && bottom($(this)) > bottom(scrollbar)) {

                  fakecontent.width($(this).get(0).scrollWidth);

                  fakecontent.height(1);

                  active = $(this);

              }

          });

          fit(active);

          return active;

      }

      

      function fit(active) {

          if (!active.length) return scrollbar.hide();

          scrollbar.css({left: active.offset().left, width:active.width()});

          fakecontent.width($(this).get(0).scrollWidth);

          fakecontent.height(1);

          delete lastScroll;

      }

      

      function onscroll(){

          var oldactive = active;

          active = find_active();

          if (oldactive.not(active).length) {

              oldactive.unbind('scroll', update);

          }

          if (active.not(oldactive).length) {

              active.scroll(update);

          }

          update();

      }

      

      var lastScroll;

      function scroll() {

          if (!active.length) return;

          if (scrollbar.scrollLeft() === lastScroll) return;

          lastScroll = scrollbar.scrollLeft();

          active.scrollLeft(lastScroll);

      }

      

      function update() {

          if (!active.length) return;

          if (active.scrollLeft() === lastScroll) return;

          lastScroll = active.scrollLeft();

          scrollbar.scrollLeft(lastScroll);

      }

      

      scrollbar.scroll(scroll);

      

      onscroll();

      $(window).scroll(onscroll);

      $(window).resize(onscroll);

  });



    $(function () {

      var w = $("#container").width();



      $(".container").width(w);

      $(".navbar-inner").width(w);

      $(".navbar").width(w);

      $("#container").width(w);

      $(".fix_img").width(w);

      $(".footer-nav").width(w);

      $("footer").width(w);



        setNavigation();

        $('.home').click(function(){



          var hrefval = $(this).attr("data");

          

              if(hrefval != "#") {

                closeSidepage('.slide-content');

                openSidepage(hrefval);



                $('.nav li').removeClass('active');



                $(this).closest('li').addClass('active');

                $(this).closest('li').parents('li').addClass('active');



                $("html, body").animate({ scrollTop: 0 }, 1);

              }



        });



        

        $('.png').click(function(){

          $('#support').animate({

            height: '300px'

          }, 300);

        });

        $('.close').click(function(){

          $('#support').animate({

            height: '22px'

          }, 300);

        });





      

    });





      function openSidepage(id) {

        $(id).css({display: "block"});

        $(id).animate({

          left: '0px'

        }, 500, 'easeOutBack'); 

      }

      

      function closeSidepage(id){

        

        $(id).animate({

          left: '-1500px'

        }, 100, 'easeOutQuint');  

        $(id).css({left: "-1500px",display: "none"});

      }



    function setNavigation() {

        var path = window.location.pathname;

        path = path.replace(/^\/([^\/]*).*$/, '/$1');

        path = decodeURIComponent(path);



        $(".nav a").each(function () {

            var href = "/"+$(this).attr('data');



            if (path === href) {

                $(this).closest('li').addClass('active');

                $(this).closest('li').parents('li').addClass('active');



            }

            if (window.location.hash == $(this).attr("data")) {

              var hrefval = $(this).attr("data");

          

              if(hrefval != "#") {

                closeSidepage('.slide-content');

                openSidepage(hrefval);



                $(this).closest('li').addClass('active');

                $(this).closest('li').parents('li').addClass('active');



                $("html, body").animate({ scrollTop: 0 }, 1);

              }

            }

            

        });



        $(".sidebar-menu a").each(function () {

            var href = "/"+$(this).attr('data');



            if (path === href) {

                $(this).closest('li').addClass('active');

                $(this).closest('li').parents('li').addClass('active');



            }

            if (window.location.hash == $(this).attr("data")) {

              var hrefval = $(this).attr("data");

          

              if(hrefval != "#") {

                closeSidepage('.slide-content');

                openSidepage(hrefval);



                $(this).closest('li').addClass('active');

                $(this).closest('li').parents('li').addClass('active');



                $("html, body").animate({ scrollTop: 0 }, 1);

              }

            }

            

        });



        if (path == "" && window.location.hash == "") {

            closeSidepage('.slide-content');

            openSidepage('#index');



            $('li').first().addClass('active');



        }

    }





    /*$(function(){

      $(".table_data").colResizable({

        liveDrag:true,

        gripInnerHtml:"<div class='grip'></div>", 

        draggingClass:"dragging"

      });

    });*/



    /*var refreshId = setInterval(function(){  

    $.ajax({

      type: "POST",

      url: "<?php echo BASE_URL ?>/admin/notification",

      data: 'data=1', // or any data you want to send

      cache: false,

      success: function(html){

       if (html != parseInt(html, 10)) {

          html = 0;

        }

      $('#nfc_count').text(html).fadeIn('fast'); // response from server side process

      }

    });

    },10000);*/



   var check_lock_user = 0;

    $.ajax({

      type: "POST",

      url: "<?php echo BASE_URL ?>/admin/checklockuser",

      data: "data=<?php echo isset($_SESSION['userid_logined'])?$_SESSION['userid_logined']:0 ?>", // or any data you want to send

      cache: false,

      success: function(html){

        check_lock_user = html;

        if (check_lock_user==1) {

          $.ajax({

            type: "GET",

            url: "<?php echo BASE_URL ?>/user/logout",

            data: "data=1", // or any data you want to send

            cache: false,

            success: function(html){

              window.location.href = "<?php echo BASE_URL ?>";

            }

          });

        };

      }

    });



    $(document).ready(function () {

            $("#btnExport").click(function () {

                $("#tblExport").battatech_excelexport({

                    containerid: "tblExport"

                   , datatype: 'table'

                });

            });

        });



    /*function flashtext(ele, col) {

            var tmpColCheck = document.getElementById(ele).style.color;



            if (tmpColCheck === 'white') {

                document.getElementById(ele).style.color = col;

            } else {

                document.getElementById(ele).style.color = 'white';

            }

        }



        setInterval(function () {

            flashtext('nfc_count', 'red');

        }, 500); //set an interval timer up to repeat the function



    $(document).ready(function(){

          $(':input').live('focus',function(){

              $(this).attr('autocomplete', 'off');

          });

      });*/

    <?php if (isset($_SESSION['userid_logined']) && ($_SESSION['role_logined'] != 1 && $_SESSION['role_logined'] != 2) ) { ?>

      $(document).ready(function(){
          $('#doaction').attr('disabled',true);
          $('#action').attr('disabled',true);
          $('.btn-danger').each(function(){
            if ($(this).attr("onclick")) {
              $(this).hide();
            }
          });

      });
    <?php } ?>

    $(document).ready(function () {
      var h = $('.table_data').height();
      if (h > 150) {
        $("#sl_vehicle").chosen();
        $("#sl_nv").chosen();
        $("#sl_status").chosen();
      }

    });

      </script>

</head>

<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <div id="ajax_loader" style="position: fixed; left: 50%; top: 50%; margin-left : -16px; margin-top : -16px; z-index:999999;">

      <img src="<?php echo BASE_URL ?>/public/img/loader-gears.gif">

  </div>

  <header class="main-header">

    <!-- Logo -->

    <a href="<?php echo BASE_URL ?>" class="logo">

      <!-- mini logo for sidebar mini 50x50 pixels -->

      <span class="logo-mini"><b>WMS</b></span>

      <!-- logo for regular state and mobile devices -->

      <span class="logo-lg"><b>WMS</b></span>

    </a>

    <!-- Header Navbar: style can be found in header.less -->

    <nav class="navbar navbar-static-top">

      <!-- Sidebar toggle button-->

      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">

        <span class="sr-only">Toggle navigation</span>

      </a>



      <div class="navbar-custom-menu">

        

          <!-- Messages: style can be found in dropdown.less-->

          

          <!-- Notifications: style can be found in dropdown.less -->

          

          <!-- Tasks: style can be found in dropdown.less -->

          

          <!-- User Account: style can be found in dropdown.less -->

          <ul class="nav navbar-nav">

          <!-- Messages: style can be found in dropdown.less-->

          <li class="dropdown messages-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-envelope-o"></i>

              <span class="label label-success">4</span>

            </a>

          </li>

          <!-- Notifications: style can be found in dropdown.less -->

          <li class="dropdown notifications-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-bell-o"></i>

              <span class="label label-warning">10</span>

            </a>

          </li>

          <!-- Tasks: style can be found in dropdown.less -->

          <li class="dropdown tasks-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-flag-o"></i>

              <span class="label label-danger">9</span>

            </a>

          </li>

          <!-- User Account: style can be found in dropdown.less -->

          <li class="dropdown user user-menu">

            <!-- Kiem tra dang nhap -->

            <?php 

            if ($_SESSION) {

              ?>

              <a class="logined" href="<?php echo $this->url('user/logout') ?>">&nbsp; | Logout</a><a class="logined" href="<?php echo BASE_URL.'/user/info/'.$_SESSION['userid_logined'] ?>"><b><i><?php echo $_SESSION['user_logined']; ?> </i></b></a>

              <?php

            }

            else{

              ?>

              <a class="logined" href="<?php echo $this->url('user/login') ?>">Login</a>

              <?php

            }

            ?>

            <!-- end -->

          </li>

          <!-- Control Sidebar Toggle Button -->

        </ul>

          

          <!-- Control Sidebar Toggle Button -->

          

      </div>

    </nav>

  </header>

  <!-- Left side column. contains the logo and sidebar -->

  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->

    <section class="sidebar">

      <div class="user-panel">

          <button type="button" class="btn btn-block btn-primary" onClick="javascript:window.location.href='<?php echo $this->url('shipment') ?>'">

            <i class="fa  fa-pencil-square-o"></i>

          </button>

      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->

      <ul class="sidebar-menu">

        <?php if ($_SESSION) { ?>

        <li class="header">QUẢN TRỊ</li>

        <li class="treeview">

          <a data="admin" href="<?php echo $this->url('admin') ?>">

            <i class="fa fa-home"></i> <span>Trang chủ</span>

          </a>

        </li>

        <li>

          <a data="#" href="#">

            <i class="fa fa-fw fa-line-chart text-aqua"></i>

            <span>Báo cáo</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="revenue" href="<?php echo $this->url('revenue') ?>"><i class="fa fa-fw fa-bar-chart text-aqua"></i>Doanh thu</a></li>
            <li><a data="costs" href="<?php echo $this->url('costs') ?>"><i class="fa fa-fw fa-dollar text-aqua"></i>Chi phí</a></li>
            

          </ul>

        </li>

        <li>

          <a data="#" href="#">

            <i class="fa fa-fw fa-money text-aqua"></i>

            <span>Tiền mặt - Tiền gửi</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="receiptvoucher" href="<?php echo $this->url('receiptvoucher') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Thu</a></li>
            <li><a data="paymentvoucher" href="<?php echo $this->url('paymentvoucher') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi</a></li>
            
            <li><a data="bankbalance" href="<?php echo $this->url('bankbalance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Số dư tài khoản</a></li>
            <li><a data="bank" href="<?php echo $this->url('bank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục tài khoản</a></li>

          </ul>

        </li>

        <li>

          <a data="#" href="#">

            <i class="fa fa-fw fa-pie-chart text-aqua"></i>

            <span>Công nợ</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li>
              <a data="receivable" href="<?php echo $this->url('receivable') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phải thu</a>
              <ul class="treeview-menu">
                <li><a data="receivable" href="<?php echo $this->url('receivable') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Tổng hợp</a></li>
                <li><a data="receivable/customer" href="<?php echo $this->url('receivable/customer') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Chi tiết</a></li>
              </ul>
            </li>
            <li>
              <a data="payable" href="<?php echo $this->url('payable') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phải trả</a>
              <ul class="treeview-menu">
                <li><a data="payable" href="<?php echo $this->url('payable') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Tổng hợp</a></li>
                <li><a data="payable/customer" href="<?php echo $this->url('payable/customer') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Chi tiết</a></li>
                
              </ul>
            </li>

          </ul>

        </li>

        <li><a data="sell" href="<?php echo $this->url('sell') ?>"><i class="fa fa-fw fa-clipboard text-aqua"></i>Đơn hàng</a></li>

        <li><a data="shipmentlist" href="<?php echo $this->url('shipmentlist') ?>"><i class="fa fa-fw fa-file-text-o text-aqua"></i>Bảng kê</a></li>

        <li><a data="exvat" href="<?php echo $this->url('exvat') ?>"><i class="fa fa-fw fa-calculator text-aqua"></i>Hóa đơn</a></li>

        <li><a data="sparepart" href="<?php echo $this->url('sparepart') ?>"><i class="fa fa-fw fa-dropbox text-aqua"></i>Danh sách nguyên vật liệu</a></li>

        <li><a data="product" href="<?php echo $this->url('product') ?>"><i class="fa fa-fw fa-cubes text-aqua"></i>Sản phẩm</a></li>

        <li><a data="importstock" href="<?php echo $this->url('importstock') ?>"><i class="fa fa-fw fa-download text-aqua"></i>Nhập kho</a></li>

        <li><a data="stock" href="<?php echo $this->url('stock') ?>"><i class="fa fa-fw fa-database text-aqua"></i>Tồn kho</a></li>

        <li><a data="cost" href="<?php echo $this->url('cost') ?>"><i class="fa fa-fw fa-dollar text-aqua"></i>Chi phí sản xuất</a></li>

        <li><a data="customer" href="<?php echo $this->url('customer') ?>"><i class="fa fa-fw fa-users text-aqua"></i>KH - NCC - Nhân viên</a></li>

        <li><a data="costlist" href="<?php echo $this->url('costlist') ?>"><i class="fa fa-fw fa-list-ul text-aqua"></i>Danh mục chi phí</a></li>


        <?php if ($_SESSION['role_logined'] == 1) { ?>

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-cogs"></i>

            <span>Hệ thống</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="user" href="<?php echo $this->url('user') ?>"><i class="fa fa-fw fa-user text-aqua"></i>Tài khoản</a></li>

            <li><a data="backup" href="<?php echo $this->url('backup') ?>"><i class="fa fa-fw fa-refresh text-aqua"></i>Sao lưu & Phục hồi</a></li>

          </ul>

        </li>

        <?php } ?>

        

        <?php } ?>

      </ul>

    </section>

    <!-- /.sidebar -->

  </aside>



  <!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">

    <!-- Content Header (Page header) -->

    



    <!-- Main content -->

    <section class="content">

      <!-- Small boxes (Stat box) -->

      <div class="row">

        <div class="col-md-12 fixed-scrollbar">

          <?php echo $content; ?>

        </div>

        <!-- ./col --> 

      </div>

      <!-- /.row -->



    </section>

    <!-- /.content -->

    

  </div>

  <!-- /.content-wrapper -->

  <footer class="main-footer">

    <div class="pull-right hidden-xs">

      <b>Version</b> 3.0

    </div>

    <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>

  </footer>



  <!-- Control Sidebar -->

  

  <!-- /.control-sidebar -->

  <!-- Add the sidebar's background. This div must be placed

       immediately after the control sidebar -->

  <div class="control-sidebar-bg"></div>

</div>

<!-- ./wrapper -->





<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<script>

  $.widget.bridge('uibutton', $.ui.button);

</script>

<!-- Bootstrap 3.3.6 -->

<script src="<?php BASE_URL ?>/public/js/adminbar/bootstrap/js/bootstrap.min.js"></script>

<!-- Morris.js charts -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.min.js"></script>

<!-- jQuery Knob Chart -->

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/knob/jquery.knob.js"></script>

<!-- daterangepicker -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Bootstrap WYSIHTML5 -->

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<!-- AdminLTE App -->

<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/app.min.js"></script>

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->

<!-- AdminLTE for demo purposes -->

<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/demo.js"></script>

<script type="text/javascript">

$( document ).ajaxStart(function() {

  $("#ajax_loader").fadeIn(200);

  $('input[type="submit"]').attr('disabled',true);
  $('button[type="submit"]').attr('disabled',true);

});

$( document ).ajaxComplete(function() {

  $("#ajax_loader").fadeOut(200);

  $('input[type="submit"]').attr('disabled',false);
  $('button[type="submit"]').attr('disabled',false);

});

$(window).load(function() { 

  $("#ajax_loader").fadeOut(200);

});

</script>

</body>

</html>